### ISSUE TITLE
Schema version stuck at 7

### ISSUE THREAD

**Issue by eraffel-MDSol** [frankhommers/Hangfire.PostgreSql#105]
If you look at the Install.v#.sql files, starting at v8 and up, the checks within the files are one number behind the filename. This is causing the v8 install to never be run at all, and for the value of version in the schema table to be left at 7.

**Comment by mbrookson** [comment]
Noticed this issue too. When running my application on macOS in debug mode, I am seeing an error being thrown with the following stack trace.

`Npgsql.PostgresException: P0001: version-already-applied
  at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:1012
  at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:1032
  at at System.Threading.Tasks.ValueTask`1.get_Result()
  at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming) in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:489
  at Npgsql.NpgsqlDataReader.NextResult() in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:332
  at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:1217
  at at System.Threading.Tasks.ValueTask`1.get_Result()
  at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:1042
  at Npgsql.NpgsqlCommand.ExecuteNonQuery() in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:1025
  at at Hangfire.PostgreSql.PostgreSqlObjectsInstaller.Install(NpgsqlConnection connection, String schemaName)`

When looking in the `hangfire.schema` table, the version is at 7 so it seems like it's got stuck.
