### ISSUE TITLE
duplicate key value violates unique constraint "lock_resource_key" - HangFire:recurring-jobs:lock

### ISSUE THREAD

**Issue by Rick45** [frankhommers/Hangfire.PostgreSql#107]
Hi, 
I'm getting some random errors when inserting in the Lock table.

```

at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1032
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming) in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 467
   at Npgsql.NpgsqlDataReader.NextResult() in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 332
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1219
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1042
   at Npgsql.NpgsqlCommand.ExecuteNonQuery() in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1025
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in C:\projects\dapper\Dapper\SqlMapper.cs:line 2827
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in C:\projects\dapper\Dapper\SqlMapper.cs:line 570
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 443
   at Hangfire.PostgreSql.PostgreSqlDistributedLock.PostgreSqlDistributedLock_Init_Transaction(String resource, TimeSpan timeout, IDbConnection connection, PostgreSqlStorageOptions options) in C:\Development\GiutHub_Samples\Hangfire.PostgreSql-master\src\Hangfire.PostgreSql\PostgreSqlDistributedLock.cs:line 77
```

in the PostgreSQL server i have the next logs:

```
2019-03-27 10:50:00 WET ERROR:  duplicate key value violates unique constraint "lock_resource_key"
2019-03-27 10:50:00 WET DETAIL:  Key (resource)=(HangFire:recurring-jobs:lock) already exists.
2019-03-27 10:50:00 WET STATEMENT:
        INSERT INTO "sdgbc"."lock"("resource", "acquired")
        SELECT $1, $2
        WHERE NOT EXISTS (
            SELECT 1 FROM "sdgbc"."lock"
            WHERE "resource" = $1
        )
2019-03-27 10:57:00 WET ERROR:  duplicate key value violates unique constraint "lock_resource_key"
2019-03-27 10:57:00 WET DETAIL:  Key (resource)=(HangFire:recurring-jobs:lock) already exists.
2019-03-27 10:57:00 WET STATEMENT:
        INSERT INTO "sdgbc"."lock"("resource", "acquired")
        SELECT $1, $2
        WHERE NOT EXISTS (
            SELECT 1 FROM "sdgbc"."lock"
            WHERE "resource" = $1
        )
2019-03-27 10:58:00 WET ERROR:  duplicate key value violates unique constraint "lock_resource_key"
2019-03-27 10:58:00 WET DETAIL:  Key (resource)=(HangFire:recurring-jobs:lock) already exists.
2019-03-27 10:58:00 WET STATEMENT:
        INSERT INTO "sdgbc"."lock"("resource", "acquired")
        SELECT $1, $2
        WHERE NOT EXISTS (
            SELECT 1 FROM "sdgbc"."lock"
            WHERE "resource" = $1
        )

```

**Comment by frankhommers** [comment]
You mean random moments? Or random errors?

**Comment by frankhommers** [comment]
Closed due to inactivity.

**Comment by AbrahamLopez10** [comment]
I'm getting the same issue as well, as shown in this extract from my logs:

```
2020-08-26 09:34:25 UTC:172.31.13.198(45880):hangfire@hangfire:[29745]:
STATEMENT:  
	INSERT INTO "hangfire"."lock"("resource", "acquired") 
	SELECT 'HangFire:locks:schedulepoller', '2020-08-27 10:58:51'
	WHERE NOT EXISTS (
	    SELECT 1 FROM "hangfire"."lock" 
	    WHERE "resource" = 'HangFire:locks:schedulepoller'
	)

2020-08-26 09:34:25 UTC:172.31.13.198(45880):hangfire@hangfire:[29745]:
DETAIL:  Key (resource)=(HangFire:locks:schedulepoller) already exists.

2020-08-26 09:34:25 UTC:172.31.13.198(45880):hangfire@hangfire:[29745]:
ERROR:  duplicate key value violates unique constraint "lock_resource_key"
```

This is happening several times each hour, and is causing a lot of errors in the logs.

My Hangfire application is using 2 workers and running in .NET Core 3.1 with the following dependency versions:

- EF Core 3.1.7
- Npgsql.EntityFrameworkCore.PostgreSQL 3.1.4.
- Hangfire.Core 1.7.12
- Hangfire.AspNetCore 1.7.12

Could be a concurrency issue due to the 2 workers maybe using transactions and trying to create a lock at the same time? Specially considering PostgreSQL's default transaction isolation level (read commited) allows nonrepeatable/phantom reads.

**Comment by AbrahamLopez10** [comment]
@frankhommers , I was wondering if you had any thoughts on the _"duplicate key value violates unique constraint "lock_resource_key""_ error appearing in PostgreSQL logs?

Is it because of the Hangfire workers each trying to acquire a lock for a job at the same time?

Also, note that I'm getting many _"could not serialize access due to concurrent update"_ errors too. Could it be related to the transaction isolation level the Hangfire.PostgreSQL package uses?

Thanks for your time.

**Comment by jenswachtel** [comment]
We unfortunately started to experience this as well since we added 2 servers. We always had only one but now this seems to have started to happen

**Comment by borgez** [comment]
SourceContext
Hangfire.PostgreSql.PostgreSqlDistributedLock
State
HangFire:locks:schedulepoller: Failed to lock with transaction
ThreadName
DelayedJobScheduler #1
Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "lock_resource_key"
   at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2822
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 572
   at Hangfire.PostgreSql.PostgreSqlDistributedLock.PostgreSqlDistributedLock_Init_Transaction(String resource, TimeSpan timeout, IDbConnection connection, PostgreSqlStorageOptions options)
  Exception data:
    Severity: ERROR
    SqlState: 23505
    MessageText: duplicate key value violates unique constraint "lock_resource_key"
    Detail: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
    SchemaName: services_hangfire
    TableName: lock
    ConstraintName: lock_resource_key
    File: nbtinsert.c
    Line: 656
    Routine: _bt_check_unique

**Comment by borgez** [comment]
@frankhommers maybe add catch PostgresException with message "duplicate key value violates unique constraint "lock_resource_key"" if this behavior is ok

**Comment by jblackwood12** [comment]
We're also experiencing this, using just 2 workers. 

Here's an exception recorded in Kibana:

`
Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "lock_resource_key"
   at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action2 paramReader) in /_/Dapper/SqlMapper.cs:line 2822
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 572
   at Hangfire.PostgreSql.PostgreSqlDistributedLock.PostgreSqlDistributedLock_Init_Transaction(String resource, TimeSpan timeout, IDbConnection connection, PostgreSqlStorageOptions options)
  Exception data:
    Severity: ERROR
    SqlState: 23505
    MessageText: duplicate key value violates unique constraint "lock_resource_key"
    Detail: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
    SchemaName: hangfire
    TableName: lock
    ConstraintName: lock_resource_key
    File: nbtinsert.c
    Line: 527
    Routine: _bt_check_unique
`

**Comment by ngallegos** [comment]
I am running into this issue as well, @frankhommers. Is there any update on whether this behavior is okay or if there's a workaround?

**Comment by josuedallagnese** [comment]
We have this exception with a single instance, but I don't know if this behavior is ok.

**Comment by pkpthegreat1** [comment]
@frankhommers , is there any update on this issue, i'm also getting same error. Npgsql.PostgresException
23505: duplicate key value violates unique constraint "lock_resource_key" on my worker service.

**Comment by MarcinWorkDev** [comment]
+1
2 servers, 1 application. .net 5.0

**Comment by frankhommers** [comment]
I haven't looked into this yet, I could use some help or a pr.

It does not happen in my applications....

**Comment by frankhommers** [comment]
@pkpthegreat1 @ngallegos 
It should be fixed in the next version.

@vytautask Can you test and deploy a new version to nuget?

**Comment by vytautask** [comment]
Version 1.8.5 released. Had to do some hotfixes but, overall, seems to be OK.

**Comment by francisfdo-ggl** [comment]
Did the fix worked ?
