### ISSUE TITLE
"Keyword not supported: data source" error

### ISSUE THREAD

**Issue by ajitgoel** [frankhommers/Hangfire.PostgreSql#117]
I am sure that this could be a newbie question. I am getting a `System.ArgumentException: 'Keyword not supported: data source'` error when trying to use this package. What am I missing? 

`Startup.cs`
 ```
public void ConfigureServices(IServiceCollection services)
    {
      services.AddHangfire(config => config.UsePostgreSqlStorage(Configuration.GetConnectionString("PostgresConnectionString")));
}
```
**AppSettings.json**
```
"ConnectionStrings": {
    "PostgresConnectionString": "Data Source=<ServerName>;location=<DatabaseName>;User ID=<UserId>;password=<Password>;",
  },
```
**StackTrace:**
```
at Npgsql.NpgsqlConnectionStringBuilder.GetProperty(String keyword) in C:\projects\npgsql\src\Npgsql\NpgsqlConnectionStringBuilder.cs:line 244
at Npgsql.NpgsqlConnectionStringBuilder.set_Item(String keyword, Object value) in C:\projects\npgsql\src\Npgsql\NpgsqlConnectionStringBuilder.cs:line 172
at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
at Hangfire.PostgreSql.PostgreSqlStorage.CreateAndOpenConnection()
at Hangfire.PostgreSql.PostgreSqlStorage..ctor(String nameOrConnectionString, PostgreSqlStorageOptions options)
at Hangfire.PostgreSql.PostgreSqlBootstrapperConfigurationExtensions.UsePostgreSqlStorage(IGlobalConfiguration configuration, String nameOrConnectionString)
at Scrubber.Startup.<ConfigureServices>b__5_0(IGlobalConfiguration config) in C:\Users\AjitGoel\source\Workspaces\Workspace\Simpler.Products\SocialMediaScrubber\Scrubber\Startup.cs:line 41

```

**Comment by vytautask** [comment]
You could try a connection string like specified here: https://github.com/frankhommers/Hangfire.PostgreSql/blob/master/tests/Hangfire.PostgreSql.Tests/Utils/ConnectionUtils.cs#L17
That one template works for sure.

**Comment by frankhommers** [comment]
You should use these parameters in your connection string: https://www.npgsql.org/doc/connection-string-parameters.html

Data Source is not one of them ;-)

**Comment by mangeshgite9** [comment]
1.

**Comment by mangeshgite9** [comment]
1.
