### ISSUE TITLE
"The connection pool has been exhausted, either raise MaxPoolSize (currently 100) or Timeout (currently 15 seconds)"

### ISSUE THREAD

**Issue by ArcadeRenegade** [frankhommers/Hangfire.PostgreSql#125]
Hello, I am getting this error on my production server after updating Hangfire to v1.7.6 and Hangfire.PostgreSQL to v1.6.2.

Background Jobs and the Hangfire Dashboard both get hung. Restarting the web servers temporarily fixes the issue.

Any ideas why this is happening? Seems like connections using the pool are not closing now for some reason.

```
[Debug] Hangfire.Processing.BackgroundExecution: Execution loop RecurringJobScheduler:cc0bfa8f caught an exception and will be retried in 00:00:16 Npgsql.NpgsqlException (0x80004005): The connection pool has been exhausted, either raise MaxPoolSize (currently 100) or Timeout (currently 15 seconds)
at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Npgsql.NpgsqlConnection.Open()
at Hangfire.PostgreSql.PostgreSqlStorage.CreateAndOpenConnection()
at Hangfire.PostgreSql.PostgreSqlStorage.GetConnection()
at Hangfire.Server.RecurringJobScheduler.UseConnectionDistributedLock(JobStorage storage, Func`2 action)
at Hangfire.Server.RecurringJobScheduler.Execute(BackgroundProcessContext context)
at Hangfire.Server.BackgroundProcessDispatcherBuilder.ExecuteProcess(Guid executionId, Object state)
at Hangfire.Processing.BackgroundExecution.Run(Action`2 callback, Object state)
```

**Comment by ArcadeRenegade** [comment]
I'm temporarily reverting back to v1.6.0 as the issue doesn't seem to happen with that previous version.

**Comment by vytautask** [comment]
Same as #124

**Comment by ArcadeRenegade** [comment]
OK thanks will keep an eye on the thread
