### ISSUE TITLE
Hangfire postgreSql connection leak 

### ISSUE THREAD

**Issue by hansimehdi** [frankhommers/Hangfire.PostgreSql#127]
**When i use the dashboard and due to the state refresh max connection exception is thrown :** 

 Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
Npgsql.PostgresException (0x80004005): 53300: remaining connection slots are reserved for non-replication superuser connections
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1003
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1032
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 425
   at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\ConnectorPool.cs:line 246
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnection.cs:line 305
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnection.Open() in C:\projects\npgsql\src\Npgsql\NpgsqlConnection.cs:line 153
   at Hangfire.PostgreSql.PostgreSqlStorage.CreateAndOpenConnection()
   at Hangfire.PostgreSql.PostgreSqlStorage.GetMonitoringApi()
   at Hangfire.Dashboard.Pages.HomePage.Execute()
   at Hangfire.Dashboard.RazorPage.TransformText(String body)
   at Hangfire.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context)
   at Hangfire.Dashboard.AspNetCoreDashboardMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**This is my configuration:** 
 services.AddHangfire(configuration => configuration
                    .SetDataCompatibilityLevel(CompatibilityLevel.Version_170)
                    .UseSimpleAssemblyNameTypeSerializer()
                    .UseRecommendedSerializerSettings()
                    .UsePostgreSqlStorage(Configuration.GetConnectionString("HangfireConnection"), new PostgreSqlStorageOptions
                    {
                        PrepareSchemaIfNecessary = false,
                        QueuePollInterval = TimeSpan.FromSeconds(15)
                    }));
app.UseHangfireServer();
app.UseHangfireDashboard("/hangfire");

**Comment by vytautask** [comment]
Isn't this the same as #124?

**Comment by zdarovka** [comment]
@vytautask it is

**Comment by hansimehdi** [comment]
Thank you @vytautask for your response , i change to mssql docker container it is more stable

**Comment by strich** [comment]
Getting the same error without any hangfire code beyond simply setting it up. It appears to exhaust the max connections I have for my db server (Hosted on Digital Ocean, which limits based on node size/cost).

**Comment by hansimehdi** [comment]
@strich yes i think it is a bug and it is better to wait for the next version

**Comment by frankhommers** [comment]
@VincentVrijburg can you look at this? We suspect it's introduced by your PR.

**Comment by VincentVrijburg** [comment]
@hansimehdi @vytautask @zdarovka @strich @frankhommers 
I've found the issue in my own PR and I'm working on a fix as we speak. I'll make a new PR with the fix after I've thoroughly tested it with multiple configurations (manually and using the existing Unit tests).

And I would appreciate it if someone, who had this issue before, can test it with my PR as well when it's out. Let me know If you're able and willing to test it.

**Comment by frankhommers** [comment]
@VincentVrijburg  can you clean up PR https://github.com/VincentVrijburg/Hangfire.PostgreSql/commit/2972ab12d69c3679679d6132fcec174764477be7

By discarding changes to tests/Hangfire.PostgreSql.Tests/Hangfire.PostgreSql.Tests.csproj and tests/Hangfire.PostgreSql.Tests/Utils/ConnectionUtils.cs ?

**Comment by VincentVrijburg** [comment]
@frankhommers My apologies. It was still work in progress as I was pushing my commits to my dev branch. 

It's clean now and, most importantly, it has the fixes for this issue.
I've tested it (manually and with the Unit tests) without SSL encrypted connections. I've still got to do that though. I'll create a PR after I've done those tests ;)

**Comment by frankhommers** [comment]
No problem @VincentVrijburg ! At least you are making progress on this ;-)

**Comment by VincentVrijburg** [comment]
There you go, a PR with a fix for this issue #127 and issue #124 (same problem).

Note: I've tested both Non-SSL and SSL encrypted connections (manually and using the existing Unit tests) and they all passed my tests.

**Comment by vytautask** [comment]
Cheers! Thank you very much!
Tested myself. Seems to work. Uploaded to nuget.org, now let's get the feedback from the folks here ;)

**Comment by vytautask** [comment]
Let's keep the issue opened until we have a confirmation it's fixed.

**Comment by KirillOFF** [comment]
v.1.6.3 works for me. Thank you!

**Comment by frankhommers** [comment]
Great work  @VincentVrijburg !
Thanks that you took over @vytautask  ;-)

**Comment by VictorUUsoro** [comment]
@VincentVrijburg @vytautask 
HangFire.PostgreSql --version 1.6.3
I had to restore this from NuGet today, and it works.
Thanks, guys
