### ISSUE TITLE
nodatime serialization support

### ISSUE THREAD

**Issue by fantasticfears** [frankhommers/Hangfire.PostgreSql#135]
I realize `Instant` can't be saved within a postgresql database because it can't be serialized. Npgsql supports Nodatime with EF Core where it makes sense for us to utilize. Any thoughts about this?

**Comment by vytautask** [comment]
I do not really get it. Could you post an example of this?

**Comment by fantasticfears** [comment]
Sure. I'm building a web application that utilizes Hangfire for background processing. The project uses EF Core 3.0 and Npgsql with `Npgsql.EntityFrameworkCore.PostgreSQL.NodaTime`. I want to use PostgreSQL as background storage for Hangfire queue. 
But the issues come across when I try to enqueue a job (without any NodaTime type and dependency). An invalid case exception was thrown when the plugin tries to serialize time related varaiables. The latter package probably removes the TimestampHandler as I read from a comment on GitHub.
Related Exception:

**Comment by st1pps** [comment]
I do have the same problem and the same setup. 

```
System.InvalidCastException: Can't write CLR type System.DateTime with handler type TimestampHandler
   at lambda_method(Closure , NpgsqlTypeHandler , Object , NpgsqlLengthCache& , NpgsqlParameter )
   at Npgsql.TypeHandling.NpgsqlSimpleTypeHandler`1.ValidateObjectAndGetLength(Object value, NpgsqlLengthCache& lengthCache, NpgsqlParameter parameter)
   at Npgsql.NpgsqlParameter.ValidateAndGetLength()
   at Npgsql.NpgsqlCommand.ValidateParameters(ConnectorTypeMapper typeMapper)
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1062
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in C:\projects\dapper\Dapper\SqlMapper.cs:line 1081
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 723
   at Hangfire.PostgreSql.PostgreSqlConnection.CreateExpiredJob(Job job, IDictionary`2 parameters, DateTime createdAt, TimeSpan expireIn)
   at Hangfire.Client.CoreBackgroundJobFactory.<>c__DisplayClass14_0.<Create>b__2(Int32 _)
   at Hangfire.Client.CoreBackgroundJobFactory.RetryOnException[T](Int32& attemptsLeft, Func`2 action)
--- End of stack trace from previous location where exception was thrown ---
   at Hangfire.Client.CoreBackgroundJobFactory.RetryOnException[T](Int32& attemptsLeft, Func`2 action)
   at Hangfire.Client.CoreBackgroundJobFactory.Create(CreateContext context)
   at Hangfire.Client.BackgroundJobFactory.<>c__DisplayClass12_0.<CreateWithFilters>b__0()
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
   at Hangfire.Client.BackgroundJobFactory.<>c__DisplayClass12_1.<CreateWithFilters>b__2()
   at Hangfire.Client.BackgroundJobFactory.CreateWithFilters(CreateContext context, IEnumerable`1 filters)
   at Hangfire.Client.BackgroundJobFactory.Create(CreateContext context)
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
```

**Comment by frankhommers** [comment]
Do we need to expose some kind of even or action which enables this type to be registered?

**Comment by fantasticfears** [comment]
Good question. The global mapper enabled seems not playing well with UseStorage.  https://github.com/npgsql/efcore.pg/blob/dev/src/EFCore.PG.NodaTime/Extensions/NpgsqlNodaTimeDbContextOptionsBuilderExtensions.cs#L26

**Comment by fantasticfears** [comment]
In an effect of tracking this problem, I set up a debug solution with the dependencies (and hack dependencies to get it running). I don't understand what's happening yet but here is the way to reproduce so far.

1. The [CreateExpiredJob](https://bitbucket.org/fantasticfears/debug.hangfirepg/src/684643526d218ca1f79139e396571f0aad08b796/Hangfire.PostgreSql/PostgreSqlConnection.cs#lines-134) will write something with Instant.
2. [SqlMapper](https://bitbucket.org/fantasticfears/debug.hangfirepg/src/684643526d218ca1f79139e396571f0aad08b796/Dapper/SqlMapper.cs#lines-1078) is setting the command. I need to investigate info.ParamReader but it seems missing.

Without much understanding, [paramReader?.Invoke(cmd, Parameters) seems setting parameters](https://bitbucket.org/fantasticfears/debug.hangfirepg/src/f24e770ad937f44bd4cd4349be693b8f809b11da/Dapper/CommandDefinition.cs#lines-128). NodaTime.Instant gets rewritten with DateTime.
Eventually, ExecuteReaderWithFlagsFallback throws the exception in this issue.

**Comment by fantasticfears** [comment]
Now I gathered all the information. When EFCore.PG.NodaTime registers itself, it also forbids using CLR "datatime" related types. This happens at a level lower than ORM, so there is nothing that can be done.
While dapper can handle NodaTime types if a corresponding handler is registered, the `Hangfire.PostgreSql` doesn't use NodaTime. Npgsql will always refuse to work.
The workaround would be to set up a connection based nodatime support with EF Core, which is documented by Npgsql.

Nevertheless, Npgsql maintainers recommend using NodaTime. But it's up to your discretion for this package.

**Comment by frankhommers** [comment]
There are some wishes for Hangfire itself. I think the best way to deal with this package is to follow them:
https://github.com/search?q=org%3AHangfireIO+Nodatime&unscoped_q=Nodatime

So not for now.

**Comment by lnaie** [comment]
Now I ran into this too. And I have to move away from this. Now... how can't this be taken into account when the posgresql recommended way to handle datetime is nodatime?!

**Comment by cm-andrews** [comment]
I found a solution to this in
https://github.com/npgsql/efcore.pg/issues/747#issuecomment-731524614

**Comment by alastor09** [comment]
Above comment by @cm-andrews saved my day.
