### ISSUE TITLE
Timeout during counter expiration

### ISSUE THREAD

**Issue by Recodify** [frankhommers/Hangfire.PostgreSql#136]
When trying to access the ui on /hangfire, whilst the expiration manager is running, results in a 500 due to a timeout, see the console output below.

I have an aws rds snapshot which replicates the issue but have been unable to narrow down why this problem is occurring. I can share this if that would be helpful? Renaming/dropping the database and recreating a new one, resolves the issue but I'm fearful of it reoccurring at some future point. I suspect this is a problem with the postgres implementation as I've not seen this behavior against sql server before, but please do say if you think this issue should be raised against the core hangfire repo

Any guidance would be greatly appreciated. :)

```
info: Hangfire.PostgreSql.ExpirationManager[0]
      Removed 4 outdated record(s) from 'counter' table.
info: Hangfire.PostgreSql.ExpirationManager[0]
      Removed 3 outdated record(s) from 'counter' table.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/hangfire  
info: Hangfire.PostgreSql.ExpirationManager[0]
      Removed 3 outdated record(s) from 'counter' table.
info: Hangfire.PostgreSql.ExpirationManager[0]
      Removed 4 outdated record(s) from 'counter' table.
info: Hangfire.PostgreSql.ExpirationManager[0]
      Removed 3 outdated record(s) from 'counter' table.
info: Hangfire.PostgreSql.ExpirationManager[0]
      Removed 3 outdated record(s) from 'counter' table.
info: Hangfire.PostgreSql.ExpirationManager[0]
      Removed 3 outdated record(s) from 'counter' table.
info: Hangfire.PostgreSql.ExpirationManager[0]
      Removed 3 outdated record(s) from 'counter' table.
info: Hangfire.PostgreSql.ExpirationManager[0]
      Removed 3 outdated record(s) from 'counter' table.
info: Hangfire.PostgreSql.ExpirationManager[0]
      Removed 3 outdated record(s) from 'counter' table.
info: Hangfire.PostgreSql.ExpirationManager[0]
      Removed 3 outdated record(s) from 'counter' table.
info: Hangfire.PostgreSql.ExpirationManager[0]
      Removed 4 outdated record(s) from 'counter' table.
info: Hangfire.PostgreSql.ExpirationManager[0]
      Removed 3 outdated record(s) from 'counter' table.
info: Hangfire.PostgreSql.ExpirationManager[0]
      Removed 3 outdated record(s) from 'counter' table.
info: Hangfire.PostgreSql.ExpirationManager[0]
      Removed 4 outdated record(s) from 'counter' table.
info: Hangfire.PostgreSql.ExpirationManager[0]
      Removed 3 outdated record(s) from 'counter' table.
info: Hangfire.PostgreSql.ExpirationManager[0]
      Removed 4 outdated record(s) from 'counter' table.
info: Hangfire.PostgreSql.ExpirationManager[0]
      Removed 4 outdated record(s) from 'counter' table.
info: Hangfire.PostgreSql.ExpirationManager[0]
      Removed 1 outdated record(s) from 'counter' table.
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLRCCCJKTQI3", Request id "0HLRCCCJKTQI3:00000002": An unhandled exception was thrown by the application.
Npgsql.NpgsqlException (0x80004005): Exception while reading from stream ---> System.IO.IOException: Unable to read data from the transport connection: Connection timed out. ---> System.Net.Sockets.SocketException: Connection timed out
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at Npgsql.NpgsqlReadBuffer.<>c__DisplayClass31_0.<<Ensure>g__EnsureLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlReadBuffer.cs:line 154
   at Npgsql.NpgsqlReadBuffer.<>c__DisplayClass31_0.<<Ensure>g__EnsureLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlReadBuffer.cs:line 175
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 955
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming) in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 444
   at Npgsql.NpgsqlDataReader.NextResult() in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 332
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1218
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1130
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1053
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1022
   at Dapper.SqlMapper.QueryMultiple(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 998
   at Hangfire.PostgreSql.PostgreSqlMonitoringApi.<GetStatistics>b__25_0(NpgsqlConnection connection)
   at Hangfire.PostgreSql.PostgreSqlMonitoringApi.UseConnection[T](Func`2 action)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Hangfire.Dashboard.Pages.HomePage.Execute()
   at Hangfire.Dashboard.RazorPage.TransformText(String body)
   at Hangfire.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context)
   at Hangfire.Dashboard.AspNetCoreDashboardMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 30422.8985ms 500 
```

Looking at the queries running:
![image](https://user-images.githubusercontent.com/5644228/69089910-9445ab80-0a40-11ea-89d0-555f5788e112.png)

and waits:
![image](https://user-images.githubusercontent.com/5644228/69090119-a889a880-0a40-11ea-8c7c-455a9e40d8aa.png)

Versions:

```
    <PackageReference Include="Dapper" Version="1.60.1" />
    <PackageReference Include="Dapper.contrib" Version="1.60.1" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.7.5" />
    <PackageReference Include="Hangfire.Console" Version="1.4.2" />
    <PackageReference Include="Hangfire.PostgreSql" Version="1.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Owin" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="2.2.0" />
    <PackageReference Include="ncrontab" Version="3.3.1" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.1" />
    <PackageReference Include="Npgsql" Version="4.0.6" />

```

**Comment by Recodify** [comment]
Ok, this issue has occurred again. It happens when the job table grows over a certain size, at which point postgres stops using the index ix_hangfire_job_statename and instead starts to perform a seq scan.

The problem can be temporarily resolved by running the following commands:

```
DELETE FROM hangfire.job WHERE expireat IS NOT NULL; 

VACUUM ANALYZE hangfire.job; 

REINDEX TABLE hangfire.job;
```

The problem is that after a period of time the problem reoccurs again as the table grows. Comparing the implementation of SqlServerMonitoringApi.GetStatistics with PostgreSqlMonitoringApi.GetStatistics show a fairly large different in implementation.

SQL:
```
  string sql = String.Format(@"
set transaction isolation level read committed;
select count(Id) from [{0}].Job with (nolock, forceseek) where StateName = N'Enqueued';
select count(Id) from [{0}].Job with (nolock, forceseek) where StateName = N'Failed';
select count(Id) from [{0}].Job with (nolock, forceseek) where StateName = N'Processing';
select count(Id) from [{0}].Job with (nolock, forceseek) where StateName = N'Scheduled';
select count(Id) from [{0}].Server with (nolock);
select sum(s.[Value]) from (
    select sum([Value]) as [Value] from [{0}].Counter with (nolock, forceseek) where [Key] = N'stats:succeeded'
    union all
    select [Value] from [{0}].AggregatedCounter with (nolock, forceseek) where [Key] = N'stats:succeeded'
) as s;
select sum(s.[Value]) from (
    select sum([Value]) as [Value] from [{0}].Counter with (nolock, forceseek) where [Key] = N'stats:deleted'
    union all
    select [Value] from [{0}].AggregatedCounter with (nolock, forceseek) where [Key] = N'stats:deleted'
) as s;
select count(*) from [{0}].[Set] with (nolock, forceseek) where [Key] = N'recurring-jobs';
                ", _storage.SchemaName);
```

Postgres:

```
 var sql = $@"
SELECT ""statename"" ""State"", COUNT(""id"") ""Count"" 
FROM ""{_options.SchemaName}"".""job""
WHERE ""statename"" IS NOT NULL
GROUP BY ""statename"";

SELECT COUNT(*) 
FROM ""{_options.SchemaName}"".""server"";

SELECT SUM(""value"") 
FROM ""{_options.SchemaName}"".""counter"" 
WHERE ""key"" = 'stats:succeeded';

SELECT SUM(""value"") 
FROM ""{_options.SchemaName}"".""counter"" 
WHERE ""key"" = 'stats:deleted';

SELECT COUNT(*) 
FROM ""{_options.SchemaName}"".""set"" 
WHERE ""key"" = 'recurring-jobs';
";
```

As you can see, the official sql server version seems to make a number of allowances for performance with multiple query hints where as the postgres version does not. I also note that a number of changes have been made to this method during the history of this repo, so I'm wondering if perhaps there is known performance issue in this area and would welcome any comments as to the best way to proceed.

**Comment by vytautask** [comment]
Could have been solved already. If not, probably #192 would solve that.
