### ISSUE TITLE
Could not find connection string with name 'XXXContext' in application config file

### ISSUE THREAD

**Issue by pirimoglu** [frankhommers/Hangfire.PostgreSql#153]
Hi,

After upgrading 1.7.0, I'm getting below error message.

System.ArgumentException: 'Could not find connection string with name 'XXXContext' in application config file'

I think PostgreSqlStorage.cs file changes cause this error.

My code sample:

```
GlobalConfiguration.Configuration.UsePostgreSqlStorage("XXXContext");
```

Problem at PostgreSqlStorage.cs

```
	        if (IsConnectionString(nameOrConnectionString))
	        {
		        _connectionString = nameOrConnectionString;
	        }
	        else
	        {
		        throw new ArgumentException(
			        $"Could not find connection string with name '{nameOrConnectionString}' in application config file");
	        }

        private bool IsConnectionString(string nameOrConnectionString)
        {
            return nameOrConnectionString.Contains(";");
        }
```

**Comment by mo3in** [comment]
i have same problem:
`Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'nameOrConnectionString')
   at Hangfire.PostgreSql.PostgreSqlStorage..ctor(String nameOrConnectionString, Action`1 connectionSetup, PostgreSqlStorageOptions options)
   at Hangfire.PostgreSql.PostgreSqlBootstrapperConfigurationExtensions.UsePostgreSqlStorage(IGlobalConfiguration configuration, String nameOrConnectionString, Action`1 connectionSetup, PostgreSqlStorageOptions options)
   at Hangfire.PostgreSql.PostgreSqlBootstrapperConfigurationExtensions.UsePostgreSqlStorage(IGlobalConfiguration configuration, String nameOrConnectionString)
`

**Comment by vytautask** [comment]
As `System.Configuration` dependency was removed (because moved to pure netstandard2), you could directly specify the connection string (not the connection string name).
We probably need to revise documentation and maybe code on this part (maybe use `IConfiguration`?)
