### ISSUE TITLE
Hangfire Dashboard System.Data.DataException

### ISSUE THREAD

**Issue by Shield-Jaguar** [frankhommers/Hangfire.PostgreSql#162]
An unhandled exception has occurred while executing the request.
System.Data.DataException: Error parsing column 2 (lastheartbeat=2020-08-09T07:59:27Z - Object)
 ---> System.InvalidCastException: Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Deserializefc051917-bd62-4e78-9026-8633f07e8b1a(IDataReader )
   --- End of inner exception stack trace ---
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in C:\projects\dapper\Dapper\SqlMapper.cs:line 3633
   at Deserializefc051917-bd62-4e78-9026-8633f07e8b1a(IDataReader )
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in C:\projects\dapper\Dapper\SqlMapper.cs:line 1098
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 721
   at Hangfire.PostgreSql.PostgreSqlMonitoringApi.<Servers>b__13_0(IDbConnection connection)
   at Hangfire.PostgreSql.PostgreSqlStorage.UseConnection[T](Func`2 func)
   at Hangfire.PostgreSql.PostgreSqlMonitoringApi.Servers()
   at Hangfire.Dashboard.Pages.ServersPage.Execute()
   at Hangfire.Dashboard.RazorPage.TransformText(String body)
   at Hangfire.Dashboard.RazorPage.ToString()
   at Hangfire.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context)
   at Hangfire.Dashboard.AspNetCoreDashboardMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)

Some libraries used in project are:
- MiniProfiler
- EF Core 3.1 npgsql with NodaTime.

**Comment by Shield-Jaguar** [comment]
Finally figured out the issue. as EF core is adding NodaTime, all date/time related values are expected to be NodaTime specific.

Solution is to convert nodatime to convert to DateTime as required by Entities.Server class

`public class LocalDateTypeHandler : SqlMapper.TypeHandler<DateTime>
	{
		public override DateTime Parse(object value)
		{
			if (value is NodaTime.Instant instant)
			{
				return instant.ToDateTimeUtc();
			}

			throw new DataException($"Unable to convert {value} to LocalDate");
		}

		public override void SetValue(IDbDataParameter parameter, DateTime value)
		{
			parameter.Value = value;
		}
	}`

**Comment by co-dax** [comment]
Thanks @Shield-Jaguar. It works.
