### ISSUE TITLE
Exception that raised the event:Npgsql.NpgsqlException (0x80004005): Received backend message ReadyForQuery while expecting ParseCompleteMessage.

### ISSUE THREAD

**Issue by Shaddix** [frankhommers/Hangfire.PostgreSql#166]
From time to time we are seeing the following exception in our production logs:
```
Exception that raised the event:Npgsql.NpgsqlException (0x80004005): Received backend message ReadyForQuery while expecting ParseCompleteMessage. Please file a bug.
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1060
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in C:\projects\dapper\Dapper\SqlMapper.cs:line 1079
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 721
   at Hangfire.PostgreSql.PostgreSqlJobQueue.<>c__DisplayClass5_1.<Dequeue_Transaction>b__1()
   at Hangfire.PostgreSql.Utils.Utils.TryExecute[T](Func`1 func, T& result, Func`2 smoothExValidator, Nullable`1 tryCount)
   at Hangfire.PostgreSql.PostgreSqlJobQueue.Dequeue_Transaction(String[] queues, CancellationToken cancellationToken)
   at Hangfire.PostgreSql.PostgreSqlJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.PostgreSql.PostgreSqlConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.BackgroundProcessDispatcherBuilder.ExecuteProcess(Guid executionId, Object state)
   at Hangfire.Processing.BackgroundExecution.Run(Action`2 callback, Object state)
```
We don't have a stable repro for that, but we experience it ~once a month.

**Comment by Shaddix** [comment]
There's a number of issues discussing the same error in [npgsql repo](https://github.com/npgsql/npgsql/issues?q=is%3Aissue+ReadyForQuery+while+expecting+ParseCompleteMessage), with few of them related to
https://github.com/npgsql/npgsql/issues/2201#issuecomment-439884692

`Appears to be caused by multithreaded execution of SQL statements with the same connection. That seems to be the case.`

could it be the reason for error in Hangfire.PostgreSql?

**Comment by vytautask** [comment]
Is this still a problem?

**Comment by anyname2** [comment]
I have seen a similar issue in our logs today: https://github.com/HangfireIO/Hangfire/issues/1876

**Comment by vytautask** [comment]
Probably could be improved with updating npgsql to 5.0.7. But overall, does not seem like an urgent issue.

**Comment by vytautask** [comment]
Is this still a problem? I reckon npgsql was updated a little while ago.

**Comment by anyname2** [comment]
Looks like it is fixed. I haven't seen any logs like this for a while now.
