### ISSUE TITLE
MAXVALUE error on startup of Hangfire

### ISSUE THREAD

**Issue by two-thirty-seven** [frankhommers/Hangfire.PostgreSql#201]
I'm seeing this error when my Hangfire service starts up and connects to the Postgres:

`info: Hangfire.PostgreSql.PostgreSqlStorage[0]
Start installing Hangfire SQL objects...
fail: Hangfire.PostgreSql.PostgreSqlStorage[0]
Error while executing install/upgrade
Npgsql.PostgresException (0x80004005): 22023: MAXVALUE (9223372036854775807) is out of range for sequence data type integer
at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
at Npgsql.NpgsqlDataReader.NextResult()
at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
at Npgsql.NpgsqlCommand.ExecuteNonQuery()
at Hangfire.PostgreSql.PostgreSqlObjectsInstaller.Install(NpgsqlConnection connection, String schemaName)
Exception data:
Severity: ERROR
SqlState: 22023
MessageText: MAXVALUE (9223372036854775807) is out of range for sequence data type integer
Where: SQL statement "ALTER SEQUENCE hangfire.job_id_seq MAXVALUE 9223372036854775807"
PL/pgSQL function inline_code_block line 4 at EXECUTE
File: sequence.c
Line: 1475
Routine: init_params`

Now, I'm new to Postgres, but it seems like it's saying the column type is incorrect for the expected values? I suspect it's related to this change - https://github.com/frankhommers/Hangfire.PostgreSql/blob/master/src/Hangfire.PostgreSql/Scripts/Install.v14.sql

Oddly enough, the startup continues on and the application runs quite happily.

I'm using the postgres:latest image in my docker-compose.

**Comment by two-thirty-seven** [comment]
Not actually a bug, I think.

Looking at the migration script, it falls back on the syntax error to a alert query that works. The sequence appears to be updated ok.

`HangFire=# select * from pg_sequences where sequencename = 'job_id_seq';
 schemaname | sequencename | sequenceowner | data_type | start_value | min_value |      max_value      | increment_by | cycle | cache_size | last_value
------------+--------------+---------------+-----------+-------------+-----------+---------------------+--------------+-------+------------+------------
 hangfire   | job_id_seq   | unicorn_user  | bigint    |           1 |         1 | 9223372036854775807 |            1 | f     |          1 |         36`

**Comment by Plasma** [comment]
This was an issue (now fixed), see https://github.com/frankhommers/Hangfire.PostgreSql/issues/195#issuecomment-879716129
