### ISSUE TITLE
Error while executing install/upgrade: MAXVALUE (9223372036854775807) is out of range for sequence data type integer

### ISSUE THREAD

**Issue by AshkanAbd** [frankhommers/Hangfire.PostgreSql#204]
Hi, Today I got this error while running my app.
```
fail: Hangfire.PostgreSql.PostgreSqlStorage[0]
      Error while executing install/upgrade
      Npgsql.PostgresException (0x80004005): 22023: MAXVALUE (9223372036854775807) is out of range for sequence data type integer
         at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlDataReader.NextResult()
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteNonQuery()
         at Hangfire.PostgreSql.PostgreSqlObjectsInstaller.Install(NpgsqlConnection connection, String schemaName)
        Exception data:
          Severity: ERROR
          SqlState: 22023
          MessageText: MAXVALUE (9223372036854775807) is out of range for sequence data type integer
          Where: SQL statement "ALTER SEQUENCE hangfire.job_id_seq MAXVALUE 9223372036854775807"
      PL/pgSQL function inline_code_block line 4 at EXECUTE
          File: sequence.c
          Line: 1472
          Routine: init_params
```
I use dotnet 5 with 
```
Hangfire.AspNetCore => Version="1.7.24"
Hangfire.Core => Version="1.7.24"
Hangfire.PostgreSql => Version="1.8.5.3"
```
What do you think about it?

**Comment by Frazi1** [comment]
It should be already fixed in Hangfire.PostgreSql `1.8.5.4`

**Comment by vytautask** [comment]
Seems like it's already fixed.
