### ISSUE TITLE
PostgreSqlObjectsInstaller produces invalid SQL statements with uppercase schema names in 1.8.6

### ISSUE THREAD

**Issue by cschulzsuper** [frankhommers/Hangfire.PostgreSql#216]
Hello, we are experiencing an error during the startup of Hangfire, where we use Hangfire.PostgreSQL 1.8.6 as storage provider.

```
Npgsql.PostgresException (0x80004005): 3F000: schema "hangfire" does not exist
   at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Hangfire.PostgreSql.PostgreSqlObjectsInstaller.Install(NpgsqlConnection connection, String schemaName)
  Exception data:
    Severity: ERROR
    SqlState: 3F000
    MessageText: schema "hangfire" does not exist
    Where: SQL statement "ALTER SEQUENCE Hangfire.job_id_seq AS bigint MAXVALUE 9223372036854775807"
PL/pgSQL function inline_code_block line 4 at EXECUTE
    File: namespace.c
    Line: 3052
    Routine: get_namespace_oid
```

The error is probably caused by our usage of uppercase schema names. We use `Hangfire` instead of `hangfire` as schema name.

The [PostgreSqlObjectsInstaller](https://github.com/frankhommers/Hangfire.PostgreSql/blob/master/src/Hangfire.PostgreSql/PostgreSqlObjectsInstaller.cs) replaces `hangfire` with `Hangfire` in the migration scripts ([Install.v14.sql](https://github.com/frankhommers/Hangfire.PostgreSql/blob/master/src/Hangfire.PostgreSql/Scripts/Install.v14.sql)). The replacement does not add any double quotes on uppercase schema names, which produces the invalid SQL statement.

For now, we reverted back to version 1.8.4 which does not produce any errors, but we would love to migrate to a new version.

Can you help to solve this error?

**Comment by frankhommers** [comment]
This will be fixed in the next release.

**Comment by cschulzsuper** [comment]
Thanks for the quick fix.
