### ISSUE TITLE
Relation "hangfire .jobqueue" does not exist

### ISSUE THREAD

**Issue by dkostenevich** [frankhommers/Hangfire.PostgreSql#219]
Hey guys, after update to 1.9.2 version I'm got error:
PostgresException: 42P01: relation "hangfire .jobqueue" does not exist

I'm guess that issue in space between schema and table name's (before dot).

Raw exception:
_Npgsql.PostgresException (0x80004005): 42P01: relation "hangfire .jobqueue" does not exist

POSITION: 65
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|213_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1075
   at Dapper.SqlMapper.QueryRowImpl[T](IDbConnection cnn, Row row, CommandDefinition& command, Type effectiveType) in /_/Dapper/SqlMapper.cs:line 1187
   at Dapper.SqlMapper.QuerySingle[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 794
   at Hangfire.PostgreSql.PostgreSqlJobQueueMonitoringApi.<>c__DisplayClass5_0.<GetEnqueuedAndFetchedCount>b__0(DbConnection connection)
   at Hangfire.PostgreSql.PostgreSqlStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)
   at Hangfire.PostgreSql.PostgreSqlJobQueueMonitoringApi.GetEnqueuedAndFetchedCount(String queue)
   at Hangfire.PostgreSql.PostgreSqlMonitoringApi.Queues()
   at Hangfire.Dashboard.Pages.QueuesPage.Execute()
   at Hangfire.Dashboard.RazorPage.TransformText(String body)
   at Hangfire.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context)
   at Hangfire.Dashboard.AspNetCoreDashboardMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, String matchedPath, String remainingPath)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
  Exception data:
    Severity: ERROR
    SqlState: 42P01
    MessageText: relation "hangfire .jobqueue" does not exist
    Position: 65
    File: parse_relation.c
    Line: 1355
    Routine: parserOpenTable_

**Comment by frankhommers** [comment]
Hmm, something slipped through not covered by unit tests. Thanks. It has been released.

**Comment by jherbert** [comment]
Hey, @frankhommers could you get a v1.9.3 version out with this? The v1.9.2 has a couple of other fixes I was after but was blocked on this issue.

Thanks so much!

**Comment by dkostenevich** [comment]
@jherbert 1.9.3 has been released (using it now)
https://www.nuget.org/packages/Hangfire.PostgreSql/

**Comment by jherbert** [comment]
@dkostenevich Ah my fault, was looking over on the releases page and not nuget. Thanks!
