### ISSUE TITLE
v1.9.3 Wrong Duration!

### ISSUE THREAD

**Issue by kstrophus** [frankhommers/Hangfire.PostgreSql#221]
Just updated to **v1.9.3** and now all my jobs are showing as created **5 hours** ago and duration as 5 hours, when in fact they were created a few minutes ago and executing in milliseconds! If I open the job ID link it shows "Latency" of 5 hours but execution of milliseconds.

I even wiped my Postgres dev database and recreated to see what is going on.

Revert to **v1.8.6** and duration is correct and 5 hour offset does not happen. By the way I am in EST timezone (UTC-5).

Both **v1.9.2** and **v1.9.3** has this strange behaviour.

**Comment by Plasma** [comment]
I note v1.9.1 updated Npgsql from v5 to v6 which contains breaking changes in how DateTime/Timestamps are handled, see https://www.npgsql.org/efcore/release-notes/6.0.html?tabs=annotations

I haven’t looked at these latest releases yet but perhaps it’s related

**Comment by frankhommers** [comment]
I thought that was only on timestamptz and not timestamp. We use timestamp to store UTC only.

**Comment by Plasma** [comment]
I think there’s some implicit changes, my linked post says that:

> timestamp without time zone and DateTime with Kind Local or Unspecified

And:

> Npgsql no longer performs any implicit timezone conversions when reading or writing any timestamp value - the value in the database is what you get, and the machine timezone no longer plays any role when reading/writing values.

Perhaps the frontend/other code now sees a returned (or inserted?) DateTime from the database with/without the local machine offset, like it may have done before, when inserting or rendering, or the Kind properly had now changed.

I was going to try writing a test to verify the issue was related but didn’t get around to it yet (eg check what a loaded createdat property on a Job looks like after insert).

**Comment by frankhommers** [comment]
Can you check if you have this problem with https://www.nuget.org/packages/Hangfire.PostgreSql.Npgsql5
and also with https://www.nuget.org/packages/Hangfire.PostgreSql ?

Please check only on new jobs.

Please report back as this tells us a bit more where to look.

**Comment by kstrophus** [comment]
Hi Frank, tested these in a NEW job each:

https://www.nuget.org/packages/Hangfire.PostgreSql.Npgsql5 (1.9.4)
    - Correct duration

https://www.nuget.org/packages/Hangfire.PostgreSql (1.9.4)
    - 5 hr duration

Please note: It may not be safe for the Hangfire.PostgreSql code to set the new Npgsl "_AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true)_" flag because we also use Postgres tables ourselves and can alter the DateTime behaviour.

From what I understand if using UTC then need to recreate tables with "timestamp with time zone". If using local then need to recreate tables with "timestamp without time zone".

**Comment by Plasma** [comment]
I've dug into this a bit further, the problem seems to be under Npgsql 6, that when `DateTime.UtcNow` is used during the insertion of the Job (in https://github.com/frankhommers/Hangfire.PostgreSql/blob/4c35304111248ff3ccc70179a77e06b8461a97b7/src/Hangfire.PostgreSql/PostgreSqlConnection.cs#L108 ) `Npgsql 6` is converting that to a local time and that is the value inserted into the database which seems unexpected.

I've raised an issue at https://github.com/npgsql/npgsql/issues/4208 because apparently the update should not be touching the values inserted as per https://www.roji.org/postgresql-dotnet-timestamp-mapping

> Values should never undergo any implicit timezone conversions when being read or written. Any conversions should be done by the user, making them clear and explicit in the code.

**Comment by Plasma** [comment]
Hi @frankhommers see the discussion at https://github.com/npgsql/npgsql/issues/4208 in particular my note at https://github.com/npgsql/npgsql/issues/4208#issuecomment-991992141 showing the conversion happening by Postgres due to how Npgsql now sends some timestamp values.

When using npgsql 6, I think the `timestamp without time zone` (aka `timestamp` columns) must be changed to `timestamp with time zone` (aka `timestamptz`) in the schema, in order for all UTC-based dates to be retained as UTC.

Based on my linked test output in the comment, I can see if the columns were changed to `timestamptz` but `Npgsql 5` was in use, then the returned timestamps will still retain their correct date/time values, but the `Kind` will have changed from `Unspecified` to `Local` under the old Npgsql 5 behavior.

Under npgsql 6, the new `timestamptz` will ensure the returned `Kind` is `Utc` and the value is not auto-converted from UTC to Pg TimeZone during insert (fixing this issue).

**Comment by azygis** [comment]
`timestamptz` is timestamp **without** time zone. As mentioned in the post about these data types - probably the worst alias in the world (and it shows).

**Comment by frankhommers** [comment]
What we need to do in my opinion is:

Leave all the tables as `timestamp`. Not `timestamptz`.
Then on every insert/update we need to convert all the dates using `.ToUniversalTime()`
Then on every retrievel we need to convert the dates to `.ToLocalTime()`

This way it should work in Npgsql5 and 6 without any special sauce.

**Comment by Plasma** [comment]
I’m thinking we need to bite the bullet and change to `timestamptz` to be more “correct” going forward.

If the Timezone value set on the pg server is different to the local Timezone of the servers running Hangfire that could lead to further issues calling ToLocal/ToUniversal.

I can have a go changing the columns and trying to see what impact that has on both Npgsql 5 and 6.

**Comment by frankhommers** [comment]
Just a reminder: Npgsql6 demands ToUniversalTime() for timestamptz. So I don't think it would make a difference.

**Comment by Plasma** [comment]
I've spent some time looking further into understanding the issue, its pretty nuanced due to new Npgsql behavior and PG behavior with `timestamp` vs `timestamptz` columns and if the current session time zone (see `show time zone`).

## Potential fix
A simple fix may be to just ensure the connection string sets the `Timezone=UTC` property when the database or local app server is not running in the `UTC` timezone.

## Observations
I've noted the following issues that are making this bug a bit confusing.

### 1) Only affecting installations where the session timezone is not UTC
Most installations likely use UTC on the app and database servers, which hide this issue.

Local development or some other deployments may use a non-UTC timezone for the database (or rather, the default session timezone value for postgres) which can trigger the timezone conversion issues with Npgsql 6.

### 2) AppVeyor CI timezone is likely UTC, not catching this issue
The AppVeyor CI is no doubt running in UTC (very reasonable) time zone, which is hiding the reported issue as no timezone conversions are taking place.

### 3) Tests currently failing on 1.9.5 with non-UTC session time zone
The existing `1.9.5` branch is failing CI tests if you run them with a SQL session `time zone` value set to a non-UTC value.

It's important that you set the time zone to the same machine time zone running the tests (so DateTime being translated to local time matches the npgsql time zone session value) which you can set via `set time zone +11` for UTC+11 for example.

```
[xUnit.net 00:00:18.82]     Hangfire.PostgreSql.Tests.PostgreSqlConnectionFacts.RemoveTimedOutServers_DoItsWorkPerfectly [FAIL]
[xUnit.net 00:00:30.98]     Hangfire.PostgreSql.Tests.PostgreSqlJobQueueFacts.Dequeue_ShouldLeaveJobInTheQueue_ButSetItsFetchedAtValue_WithUseNativeDatabaseTransactions [FAIL]
[xUnit.net 00:00:30.98]     Hangfire.PostgreSql.Tests.PostgreSqlWriteOnlyTransactionFacts.DecrementCounter_WithExpiry_AddsARecord_WithExpirationTimeSet [FAIL]
[xUnit.net 00:00:32.28]     Hangfire.PostgreSql.Tests.PostgreSqlJobQueueFacts.Dequeue_ShouldLeaveJobInTheQueue_ButSetItsFetchedAtValue_WithoutUseNativeDatabaseTransactions [FAIL]
[xUnit.net 00:00:52.39]     Hangfire.PostgreSql.Tests.PostgreSqlConnectionFacts.CreateExpiredJob_CreatesAJobInTheStorage_AndSetsItsParameters [FAIL]
[xUnit.net 00:00:52.40]     Hangfire.PostgreSql.Tests.PostgreSqlWriteOnlyTransactionFacts.IncrementCounter_WithExpiry_AddsARecord_WithExpirationTimeSet [FAIL]
[xUnit.net 00:00:53.47]     Hangfire.PostgreSql.Tests.PostgreSqlConnectionFacts.CreateExpiredJob_EnlistsInTransaction(completeTransactionScope: True) [FAIL]
  Failed Hangfire.PostgreSql.Tests.PostgreSqlConnectionFacts.CreateExpiredJob_EnlistsInTransaction(completeTransactionScope: True) [5 ms]
  Error Message:
   Assert.Equal() Failure
Expected: 2012-12-12T00:00:00.0000000
Actual:   2012-12-11T13:00:00.0000000Z
  Stack Trace:
     at CallSite.Target(Closure , CallSite , Type , DateTime , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Hangfire.PostgreSql.Tests.PostgreSqlConnectionFacts.<>c__DisplayClass84_0.<CreateExpiredJob_EnlistsInTransaction>b__1(NpgsqlConnection connection, PostgreSqlConnection _) in Hangfire.PostgreSql\tests\Hangfire.PostgreSql.Tests\PostgreSqlConnectionFacts.cs:line 1268
   at Hangfire.PostgreSql.Tests.PostgreSqlConnectionFacts.UseConnections(Action`2 action) in Hangfire.PostgreSql\tests\Hangfire.PostgreSql.Tests\PostgreSqlConnectionFacts.cs:line 1283
   at Hangfire.PostgreSql.Tests.PostgreSqlConnectionFacts.CreateExpiredJob_EnlistsInTransaction(Boolean completeTransactionScope) in Hangfire.PostgreSql\tests\Hangfire.PostgreSql.Tests\PostgreSqlConnectionFacts.cs:line 1263
[xUnit.net 00:00:53.48]     Hangfire.PostgreSql.Tests.PostgreSqlConnectionFacts.GetJobData_ReturnsResult_WhenJobExists [FAIL]
```

### 4) Tests in pre-npgsql6 (Hangfire.PostgreSql <= 1.8.6) succeed with non-UTC session time zone
The time zone can be a non-UTC value and the tests pass OK for `Hangfire.PostgreSql <= 1.8.6`, the last version before Npgsql 6.

## Workaround
Setting the SQL session timezone for `1.9.5` during connection to `UTC` seems to make the tests pass without any schema/code changes:

This appears to ensure even if we send a "local" timestamp its interpreted as UTC anyway:
```csharp
// Add to ConnectionUtils.CreateConnection() and ConnectionUtils.CreateMasterConnection() in Tests project
connection.Execute("SET TIME ZONE 'UTC'");
```

If a suitable workaround, would need to make appropriate adjustment in the actual processing logic/code to set the timezone as part of connection (via above SQL, or probably connection string parameter being set automatically).

## Prototyped changes

### Move to timestamptz column and adjust queries to be UTC without any conversions
I've prototyped what it may look like to move to `timestamptz` column for Npgsql 6 and necessary changes:
See https://github.com/frankhommers/Hangfire.PostgreSql/pull/230

This PR is a bit more impactful though and I am conscious of existing code that would be running during the schema changes potentially leading to issues.

### Set connection time zone to UTC automatically
We could ensure the connection string sets the `Timezone` parameter to `UTC` (forced in code) to ensure the Hangfire logic treats all timezones as UTC even if sent as a "local" DateTime when we build the connection.

### Other changes
As noted by Frank in https://github.com/frankhommers/Hangfire.PostgreSql/issues/221#issuecomment-993561044

**Comment by Plasma** [comment]
Fix applied via #234

**Comment by frankhommers** [comment]
Thanks for the extensive research BTW @Plasma !

**Comment by m0nax3** [comment]
sorry, but still bug here :)
app culture = CultureInfo.InvariantCulture
real workstation timezone = +3h
Npgsql6
dashbord displays wrong duration (and all other timings)

i've manual change columns to **timesnampz** and all become perfect, but it's not really ok when default db schema incorrect

**Comment by azygis** [comment]
True, hence the issue is still open. Even though it's fixed, the package is not published to NuGet yet.

Last I heard Frank is still working on something before releasing a new version.
