### ISSUE TITLE
BackgroundJob repeated execution and throw exception

### ISSUE THREAD

**Issue by feic8700425** [frankhommers/Hangfire.PostgreSql#242]
Hangfire.PostgreSql Ver：1.9.5

some BackgroundJob will repeated execution in the same time

error:
 at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2858
 at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 581
 at Hangfire.PostgreSql.PostgreSqlDistributedLock.TransactionLockHandler.Lock(String resource, TimeSpan timeout, IDbConnection connection, PostgreSqlStorageOptions options)
 Exception data:
 Severity: ERROR
 SqlState: 40001
 MessageText: could not serialize access due to concurrent update
 File: nodeModifyTable.c
 Line: 225
 Routine: ExecCheckHeapTupleVisibl

**Comment by azygis** [comment]
Please provide a full exception with full stack trace. This seems stripped off a lot.

**Comment by feic8700425** [comment]
Hangfire.AspNetCore Ver：1.7.28
Hangfire.PostgreSql Ver：1.9.5
Dapper Ver：2.0.123
Npgsql Ver：6.0.0

warn: Hangfire.PostgreSql.PostgreSqlDistributedLock[0]
public:job:13021394:state-lock: Failed to lock with transaction
Npgsql.PostgresException (0x80004005): 40001: could not serialize access due to concurrent update
at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|213_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean i
at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
at Npgsql.NpgsqlDataReader.NextResult()
at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
at Npgsql.NpgsqlCommand.ExecuteNonQuery()
at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2858
at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 581
at Hangfire.PostgreSql.PostgreSqlDistributedLock.TransactionLockHandler.Lock(String resource, TimeSpan timeout, IDbConnection connection, PostgreSqlStorageOptions options)
Exception data:
Severity: ERROR
SqlState: 40001
MessageText: could not serialize access due to concurrent update
File: nodeModifyTable.c
Line: 225
Routine: ExecCheckHeapTupleVisible

**Comment by azygis** [comment]
This is normal, exception is handled internally. You can configure your logger to ignore anything lower than error level with whatever logging provider you use. The log message is output to make it possible to investigate the actual exception in case there are infrastructure issues.
