### ISSUE TITLE
BackgroundJob.Schedule() Once But Enqueued Twice

### ISSUE THREAD

**Issue by feic8700425** [frankhommers/Hangfire.PostgreSql#245]
Hangfire.AspNetCore Ver：1.7.28
Hangfire.PostgreSql Ver：1.9.5
Dapper Ver：2.0.123
Npgsql Ver：6.0.0

BackgroundJob.Schedule() once, but Hangfire enqueued twice, server workers: 20

![image](https://user-images.githubusercontent.com/64301817/153796609-10c8c684-14ae-4f9e-9657-9fbc8fa8b818.png)
![image](https://user-images.githubusercontent.com/64301817/153796866-1a26a113-40ff-4c47-adc1-7b6a4f12a7b3.png)

**Comment by azygis** [comment]
Please use version 1.9.6, looking at the job timings, one job was enqueued in +8h, second one in -8h (from first job; ultimately at the same time). It looks that it might be related to the timezone issues which were fixed in the last version.

**Comment by feic8700425** [comment]
thx, I try it right now

**Comment by azygis** [comment]
@feic8700425 did you have a chance to reproduce the issue with latest version?

**Comment by feic8700425** [comment]
uat test ok yesterday, is going to be released to the production environment today
I'll check it tomorrow

**Comment by feic8700425** [comment]
System.InvalidOperationException
Could not get a value of the job parameter `CurrentUICulture`. See inner exception for details.

System.InvalidOperationException: Could not get a value of the job parameter `CurrentUICulture`. See inner exception for details.
 ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
   at System.Data.Common.DbConnectionStringBuilder.get_ConnectionString()
   at Hangfire.PostgreSql.PostgreSqlStorage.CreateAndOpenConnection()
   at Hangfire.PostgreSql.PostgreSqlStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)
   at Hangfire.Server.PerformContext.GetJobParameter[T](String name)
   --- End of inner exception stack trace ---
   at Hangfire.Server.PerformContext.GetJobParameter[T](String name)
   at Hangfire.CaptureCultureAttribute.OnPerforming(PerformingContext filterContext)
   at Hangfire.Profiling.ProfilerExtensions.InvokeAction[TInstance](InstanceAction`1 tuple)
   at Hangfire.Profiling.SlowLogProfiler.InvokeMeasured[TInstance,TResult](TInstance instance, Func`2 action, String message)
   at Hangfire.Profiling.ProfilerExtensions.InvokeMeasured[TInstance](IProfiler profiler, TInstance instance, Action`1 action, String message)
   at Hangfire.Server.BackgroundJobPerformer.InvokePerformFilter(IServerFilter filter, PerformingContext preContext, Func`1 continuation)

**Comment by feic8700425** [comment]
System.BadImageFormatException
Could not load file or assembly '<Unknown>'. Index not found. (0x80131124)

System.BadImageFormatException: Could not load file or assembly '<Unknown>'. Index not found. (0x80131124)
File name: '<Unknown>'
   at System.Reflection.RuntimeAssembly.GetType(QCallAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive, ObjectHandleOnStack assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.TypeNameParser.ResolveType(Assembly assembly, String[] names, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.TypeNameParser.ConstructType(Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.TypeNameParser.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError)
   at Hangfire.Common.TypeHelper.DefaultTypeResolver(String typeName)
   at Hangfire.Storage.InvocationData.DeserializeJob()

**Comment by feic8700425** [comment]
I got lots of error when with latest version 1.9.6
cur Scheduled Jobs count: 818

**Comment by feic8700425** [comment]
I got hundreds error in 1 mins after deployment(use version 1.9.6), and then I rollback the deployment.
I didn't check the timezone issues

**Comment by frankhommers** [comment]
Did you start fresh?

**Comment by feic8700425** [comment]
fixed by version:
Hangfire.PostgreSql Ver：1.8.6
Npgsql Ver：5.0.7
