### ISSUE TITLE
Sometime getting relation "hangfire.lock" does not exist

### ISSUE THREAD

**Issue by abhishekk478** [frankhommers/Hangfire.PostgreSql#257]
Sometimes getting below error. I checked the hangfire schema, sometime lock table doesn't created by itself, but after restarting the pods lock table gets created and starts working fine. This issue is intermittent.

      Hangfire.PostgreSql.PostgreSqlDistributedLock[0]
      HangFire:recurring-jobs:lock: Failed to remove lock
      Npgsql.PostgresException (0x80004005): 42P01: relation "hangfire.lock" does not exist
         at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlDataReader.NextResult()
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteNonQuery()
         at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2822
         at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 572
         at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 443
         at Hangfire.PostgreSql.PostgreSqlDistributedLock.TryRemoveDeadlock(String resource, IDbConnection connection, PostgreSqlStorageOptions options)
        Exception data:
          Severity: ERROR
          SqlState: 42P01
          MessageText: relation "hangfire.lock" does not exist
          Position: 13
          File: parse_relation.c
          Line: 1382
          Routine: parserOpenTable

**Comment by frankhommers** [comment]
Are you deleting this table every time? You should keep it I guess.
Are you using a cluster which is not in sync yet?

**Comment by abhishekk478** [comment]
Whenever new release deployed, database gets deleted and recreated.
I am not deleting hangfire schema or lock table explicitly.

**Comment by abhishekk478** [comment]
@Plasma In my case pods/instance are scaled down and deleted first so that the connections are terminated and then the DB is deleted, because existing connections might cause a problem for deleting the DB.
And I am not getting this issue always. It is intermittent.

**Comment by azygis** [comment]
Can you see any other logs before the exception which might show anything relevant to Hangfire?

How/when is the database created?

We run our application in docker with multiple replicas and have never experienced this, even though we also recreate the database container from scratch for our CI build.

**Comment by Plasma** [comment]
Perhaps you could add some verbose logging/review cloudtrail with time stamps to confirm order of events (stop container, container terminated, and timestamp of database delete, and timestamp of the exception error) as it feels like it could be a race condition.

**Comment by abhishekk478** [comment]
Ok, will do that.

**Comment by abhishekk478** [comment]
Steps sequence involved in release deployment according to timestamp.
1. Scaling down the pods.
2. Wiping out the database.
3. Migrating the database.
4. Deploying the image.

**Comment by frankhommers** [comment]
If scaling down means not stopping them, and between 2 and 3 they want to write a lock you'll get this error.

**Comment by abhishekk478** [comment]
We are scaling down to 0 technically stopping. Then deleting the existing the database and creating new and restore backup. After this we are deploying new image and starts the application.
I checked lock table gets created by itself on application start as I am starting a hangfire job at startup. So, it is not possible that application write a lock in between 2 and 3 because at this time application is stopped.
Most of the cases lock table created by itself on application start and works fine, but in some cases lock table doesn't created by itself and I am getting this error on application log.

**Comment by abhishekk478** [comment]
@azygis 

    Building...
    info: Hangfire.PostgreSql.PostgreSqlStorage[0]
          Start installing Hangfire SQL objects...
    info: Hangfire.PostgreSql.PostgreSqlStorage[0]
          Hangfire SQL objects installed.
    info: AWSSDK[0]
          Found AWS options in IConfiguration
    info: AWSSDK[0]
          Found credentials using the AWS SDK's default credential search
    warn: Hangfire.PostgreSql.PostgreSqlDistributedLock[0]
          HangFire:lock:recurring-job:XXXJobName: Failed to remove lock
          Npgsql.PostgresException (0x80004005): 42P01: relation "hangfire.lock" does not exist
             at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, 
    DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
             at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
             at Npgsql.NpgsqlDataReader.NextResult()
             at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken 
    cancellationToken)
             at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken 
    cancellationToken)
             at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
             at Npgsql.NpgsqlCommand.ExecuteNonQuery()
             at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) 
    in /_/Dapper/SqlMapper.cs:line 2813
             at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in 
    /_/Dapper/SqlMapper.cs:line 572
             at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 
    commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 443
             at Hangfire.PostgreSql.PostgreSqlDistributedLock.TryRemoveDeadlock(String resource, IDbConnection connection, 
    PostgreSqlStorageOptions options)
            Exception data:
              Severity: ERROR
              SqlState: 42P01
              MessageText: relation "hangfire.lock" does not exist
              Position: 13
              File: parse_relation.c
              Line: 1363
              Routine: parserOpenTable


Same warn message continued until several thousands lines.

**Comment by azygis** [comment]
Intetesting. Objects installer seems to have run without any problems. Think we need to add some debug logging there to see what (if any) scripts are actually run.

Can do that maybe today, but only @frankhommers can publish it to NuGet.

**Comment by abhishekk478** [comment]
@azygis Please wait for now, will let you know by monday, if we need to do this.
