### ISSUE TITLE
Is there any way to specify desirable transaction isolation level?

### ISSUE THREAD

**Issue by stawr93** [frankhommers/Hangfire.PostgreSql#258]
Hey there,

My application uses serializable transaction isolation level. After I added Hangfire.PostgreSql to the app and tried to create background job, I've gotten an exception:

```
Hangfire.BackgroundJobClientException: Background job creation failed. See inner exception for details.
 ---> System.ArgumentException: The transaction specified for TransactionScope has a different IsolationLevel than the value requested for the scope. (Parameter 'transactionOptions')
   at System.Transactions.TransactionScope..ctor(TransactionScopOption scopeOption, TransactionOptions transactionOptions, TransactionScopeAsyncFlowOption asyncFlowOption)
   at System.Transactions.TransactionScope..ctor(TransactionScopeOption scopeOption, TransactionOptions transactionOptions)
   at Hangfire.PostgreSql.PostgreSqlStorage.CreateTransaction(Nullable`1 isolationLevel)
   at Hangfire.PostgreSql.PostgreSqlStorage.UseTransaction[T](DbConnection dedicatedConnection, Func`3 func, Nullable`1 isolationLevel)
   at Hangfire.PostgreSql.PostgreSqlConnection.CreateExpiredJob(Job job, IDictionary`2 parameters, DateTime createdAt, TimeSpan expireIn)

<application stack trace>

```

After some code inspection, I found that transaction isolation level defaults to ReadCommitted here: https://github.com/frankhommers/Hangfire.PostgreSql/blob/master/src/Hangfire.PostgreSql/PostgreSqlStorage.cs#L282.

I was unable to find any way to specify other transaction isolation level. How can I do that? Is ReadCommitted used as default by design for some reason?

**Comment by azygis** [comment]
This is _by design_, copied over from SqlServer implementation (unfortunately I am not aware of the reasoning for such default). In case it's urgent, you are more than welcome to create a pull request, if able! Shouldn't be too hard, if I remember correctly.

**Comment by stawr93** [comment]
@azygis, yeah, that's pretty important for mine team. Fixed the issue, see my PR https://github.com/frankhommers/Hangfire.PostgreSql/pull/260

**Comment by azygis** [comment]
@frankhommers needs to push the latest nuget package to the repository.

Thank you!
