### ISSUE TITLE
PostgresException: 42P01: relation "hangfire.counter" does not exist

### ISSUE THREAD

**Issue by cosminvladutu** [frankhommers/Hangfire.PostgreSql#277]
I get this: An unhandled exception occurred while processing the request.
PostgresException: 42P01: relation "hangfire.counter" does not exist

POSITION: 64
Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|226_0(NpgsqlConnector connector, bool async, DataRowLoadingMode dataRowLoadingMode, bool readingNotifications, bool isReadingPrependedMessage)

 after adding:

            builder.Services.AddHangfire(x => x.UsePostgreSqlStorage(builder.Configuration.GetConnectionString("adminDb")));
            builder.Services.AddHangfireServer();
           
and 

 app.UseHangfireDashboard();

I get the same issue if I use app.UseHangfireServer(); instead of builder.Services.AddHangfireServer();

I guess the problem is due to the tables not being created, but don't know the cause of this.

The webApi is in dotnet 7.
The version of the package used 1.9.9

**Comment by azygis** [comment]
Please show the full stack trace.

**Comment by cosminvladutu** [comment]
PostgresException: 42P01: relation "hangfire.counter" does not exist POSITION: 64
Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|226_0(NpgsqlConnector connector, bool async, DataRowLoadingMode dataRowLoadingMode, bool readingNotifications, bool isReadingPrependedMessage)
Npgsql.NpgsqlDataReader.NextResult(bool async, bool isConsuming, CancellationToken cancellationToken)
Npgsql.NpgsqlDataReader.NextResult(bool async, bool isConsuming, CancellationToken cancellationToken)
Npgsql.NpgsqlDataReader.NextResult()
Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, bool async, CancellationToken cancellationToken)
Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, bool async, CancellationToken cancellationToken)
Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, bool wasClosed, CommandBehavior behavior) in SqlMapper.cs
Dapper.SqlMapper.QueryImpl<T>(IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in SqlMapper.cs
System.Collections.Generic.List<T>..ctor(IEnumerable<T> collection)
System.Linq.Enumerable.ToList<TSource>(IEnumerable<TSource> source)
Dapper.SqlMapper.Query<T>(IDbConnection cnn, string sql, object param, IDbTransaction transaction, bool buffered, Nullable<int> commandTimeout, Nullable<CommandType> commandType) in SqlMapper.cs
Hangfire.PostgreSql.PostgreSqlMonitoringApi+<>c__DisplayClass27_0.<GetTimelineStats>b__0(IDbConnection connection)
Hangfire.PostgreSql.PostgreSqlStorage.UseConnection<T>(DbConnection dedicatedConnection, Func<DbConnection, T> func)
Hangfire.PostgreSql.PostgreSqlMonitoringApi.UseConnection<T>(Func<IDbConnection, T> func)
Hangfire.PostgreSql.PostgreSqlMonitoringApi.GetTimelineStats(IDictionary<string, DateTime> keyMaps)
Hangfire.PostgreSql.PostgreSqlMonitoringApi.GetHourlyTimelineStats(string type)
Hangfire.PostgreSql.PostgreSqlMonitoringApi.HourlySucceededJobs()
Hangfire.Dashboard.Pages.HomePage.Execute()
Hangfire.Dashboard.RazorPage.TransformText(string body)
Hangfire.Dashboard.RazorPage.ToString()
Hangfire.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context)
Hangfire.Dashboard.AspNetCoreDashboardMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)



**raw exception details**

Npgsql.PostgresException (0x80004005): 42P01: relation "hangfire.counter" does not exist

POSITION: 64
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|226_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1075
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1094
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 734
   at Hangfire.PostgreSql.PostgreSqlMonitoringApi.<>c__DisplayClass27_0.<GetTimelineStats>b__0(IDbConnection connection)
   at Hangfire.PostgreSql.PostgreSqlStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)
   at Hangfire.PostgreSql.PostgreSqlMonitoringApi.UseConnection[T](Func`2 func)
   at Hangfire.PostgreSql.PostgreSqlMonitoringApi.GetTimelineStats(IDictionary`2 keyMaps)
   at Hangfire.PostgreSql.PostgreSqlMonitoringApi.GetHourlyTimelineStats(String type)
   at Hangfire.PostgreSql.PostgreSqlMonitoringApi.HourlySucceededJobs()
   at Hangfire.Dashboard.Pages.HomePage.Execute()
   at Hangfire.Dashboard.RazorPage.TransformText(String body)
   at Hangfire.Dashboard.RazorPage.ToString()
   at Hangfire.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context)
   at Hangfire.Dashboard.AspNetCoreDashboardMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
  Exception data:
    Severity: ERROR
    SqlState: 42P01
    MessageText: relation "hangfire.counter" does not exist
    Position: 64
    File: parse_relation.c
    Line: 1371
    Routine: parserOpenTable

**Comment by azygis** [comment]
Looks like the application is running at this point, meaning the SQL objects should be installed (unless you disabled the install explicitly, but not according to your storage registration options). If any migration fails, the logs should contain the reason why the migration failed. Please check the logs of the application startup to see what happened.

**Comment by cosminvladutu** [comment]
[hangfireissue.txt](https://github.com/frankhommers/Hangfire.PostgreSql/files/10391268/hangfireissue.txt)

I added in the txt the output after the migrations of my app finished.

**Comment by azygis** [comment]
```
Hangfire.PostgreSql.PostgreSqlStorage: Information: Start installing Hangfire SQL objects...
Hangfire.PostgreSql.PostgreSqlStorage: Information: Hangfire SQL objects installed.
Hangfire.BackgroundJobServer: Information: Starting Hangfire Server using job storage: 'PostgreSQL Server: Host: localhost, DB: Teleaid, Schema: hangfire'
Hangfire.BackgroundJobServer: Information: Using the following options for SQL Server job storage:
Hangfire.BackgroundJobServer: Information:     Queue poll interval: 00:00:15.
Hangfire.BackgroundJobServer: Information:     Invisibility timeout: 00:30:00.
Hangfire.BackgroundJobServer: Information: Using the following options for Hangfire Server:
    Worker count: 20
    Listening queues: 'default'
    Shutdown timeout: 00:00:15
    Schedule polling interval: 00:00:15
<...>
Hangfire.Server.BackgroundServerProcess: Information: Server cosmin-vladutu:9472:35fd1609 successfully announced in 166.6159 ms
Hangfire.Server.BackgroundServerProcess: Information: Server cosmin-vladutu:9472:35fd1609 is starting the registered dispatchers: ServerWatchdog, ServerJobCancellationWatcher, ExpirationManager, Worker, DelayedJobScheduler, RecurringJobScheduler...
Hangfire.Server.BackgroundServerProcess: Information: Server cosmin-vladutu:9472:35fd1609 all the dispatchers started
<...>
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (7ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
REVOKE CONNECT ON DATABASE "Teleaid" FROM PUBLIC;
SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE datname = 'Teleaid';
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (23ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
DROP DATABASE "Teleaid";
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (40ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE DATABASE "Teleaid";
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);
<...>
```

That is your issue. You are dropping and recreating the database on each application startup. Either use a different database for hangfire, or do not drop the database using EF migrations.

**Comment by cosminvladutu** [comment]
Also found the issue 
I was stupid. After creating the builder I had a reset database, just before app.Run(). This reset, re-run my migrations, but not the hangfire needed once. 

Thanks for your support!

**Comment by douglasg14b** [comment]
How do you manually run the hangfire DB object install?
