### ISSUE TITLE
Question about recurring errors

### ISSUE THREAD

**Issue by topwik** [frankhommers/Hangfire.PostgreSql#67]
I've just updated to the latest version and still see  some common errors occurring. Are we to expect to see these happen often?

> 2017-05-10 12:01:00.568 [199] INFO Hangfire.PostgreSql.PostgreSqlStorage - Start installing Hangfire SQL objects... 
> 2017-05-10 12:01:00.599 [199] ERROR Hangfire.PostgreSql.PostgreSqlStorage - Error while executing install/upgrade 

> Npgsql.PostgresException (0x80004005): 42701: column "updatecount" of relation "counter" already exists

> Npgsql.PostgresException (0x80004005): 42701: column "acquired" of relation "lock" already exists

also I'm hoping I start to see less of the following occur going forward. I mentioned these in an issue #31 before and it was closed off so I was hoping these wouldn't be popping up anymore.

I hope these don't have anything to do with retrying failed jobs. We have been seeing that retries weren't working. If a job failed, it got added to the list of retires but retry attempt count never passed 1.

Seems like retry never happen if failed to place a lock on specified resource

> Retry attempt 1 of 3: Failure sending mail. 

> Error occurred during execution of 'RecurringJobScheduler' process. Execution will be retried (attempt 155 of 2147483647) in 00:05:00 seconds. 
> Hangfire.PostgreSql.PostgreSqlDistributedLockException: Could not place a lock on the resource 'HangFire:recurring-jobs:lock': Lock timeout.

> Error occurred during execution of 'DelayedJobScheduler' process. Execution will be retried (attempt 162 of 2147483647) in 00:05:00 seconds. 
> Hangfire.PostgreSql.PostgreSqlDistributedLockException: Could not place a lock on the resource 'HangFire:locks:schedulepoller': Lock timeout.

**Comment by vytautask** [comment]
Could you, please, try to remove whole hangfire schema and try again? 
Maybe the previous update of hangfire database failed?

**Comment by frankhommers** [comment]
Closed for inactivity.

**Comment by AnthonyMastrean** [comment]
We're on these packages

```
    <PackageReference Include="Hangfire.AspNetCore" Version="1.6.22" />
    <PackageReference Include="Hangfire.PostgreSql" Version="1.5.0" />
```

And we just started seeing this error.

```
fail: Hangfire.PostgreSql.PostgreSqlStorage[0]
      Error while executing install/upgrade
Npgsql.PostgresException (0x80004005): 42701: column "updatecount" of relation "lock" already exists
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Hangfire.PostgreSql.PostgreSqlObjectsInstaller.Install(NpgsqlConnection connection, String schemaName)
fail: Hangfire.PostgreSql.PostgreSqlStorage[0]
      Error while executing install/upgrade
Npgsql.PostgresException (0x80004005): 42701: column "acquired" of relation "lock" already exists
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Hangfire.PostgreSql.PostgreSqlObjectsInstaller.Install(NpgsqlConnection connection, String schemaName)
fail: Hangfire.PostgreSql.PostgreSqlStorage[0]
      Error while executing install/upgrade
Npgsql.PostgresException (0x80004005): 42703: column "updatecount" of relation "counter" does not exist
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Hangfire.PostgreSql.PostgreSqlObjectsInstaller.Install(NpgsqlConnection connection, String schemaName)
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Overriding address(es) 'http://+:80'. Binding to endpoints defined in UseKestrel() instead.
Hosting environment: Production
Content root path: /app/web
Now listening on: https://0.0.0.0:6443
Application started. Press Ctrl+C to shut down.
```

I don't have any more info, yet, but we'll let you know.

**Comment by frankhommers** [comment]
What's the contents of the version column in your schema table?
