### ISSUE TITLE
Occasional Npgsql.PostgresException when PostgreSqlConnection.SetRangeInHash is used in filter

### ISSUE THREAD

**Issue by pieceofsummer** [frankhommers/Hangfire.PostgreSql#70]
Happens sometimes when using with Hangfire.Console:
```
Npgsql.PostgresException: 40001: could not serialize access due to read/write dependencies among transactions

   at Npgsql.NpgsqlConnector.<DoReadMessage>d__148.MoveNext()
   at Npgsql.NpgsqlConnector.<ReadMessage>d__147.MoveNext()
   at Npgsql.NpgsqlDataReader.<NextResult>d__31.MoveNext()
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.<Execute>d__70.MoveNext()
   at Npgsql.NpgsqlCommand.<ExecuteNonQuery>d__83.MoveNext()
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
   at Hangfire.PostgreSql.PostgreSqlConnection.SetRangeInHash(String key, IEnumerable`1 keyValuePairs)
   at Hangfire.Console.Server.ConsoleServerFilter.OnPerforming(PerformingContext filterContext)
   at Hangfire.Server.BackgroundJobPerformer.InvokePerformFilter(IServerFilter filter, PerformingContext preContext, Func<PerformedContext> continuation)
```

**Comment by vytautask** [comment]
It would be interesting to have a test case for this...

**Comment by vytautask** [comment]
🎆 Should be fixed now. Thanks for reporting!
